custombucket = "shivpgp-project"
table = "intellipaat"
databasehost = "database-1.cvwwkjmmcvgi.us-east-1.rds.amazonaws.com"
duser = "admin"
dpass = "admin123"
s3database = "intellipaat"
kapp = "http://192.168.1.86:31681/"
